// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: chat/v1/chat.proto

package chatv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageType int32

const (
	MessageType_MESSAGE_TYPE_UNSPECIFIED MessageType = 0
	MessageType_AUTH                     MessageType = 1
	MessageType_AUTH_OK                  MessageType = 2
	MessageType_AUTH_REJECTED            MessageType = 3
	MessageType_HEARTBEAT                MessageType = 16
	MessageType_HEARTBEAT_ACK            MessageType = 17
	MessageType_JOIN_ROOM                MessageType = 256
	MessageType_JOIN_ROOM_OK             MessageType = 257
	MessageType_LEAVE_ROOM               MessageType = 258
	MessageType_LEAVE_ROOM_OK            MessageType = 259
	MessageType_SEND_MSG                 MessageType = 272
	MessageType_RECV_MSG                 MessageType = 273
	MessageType_MSG_REJECTED             MessageType = 274
	MessageType_PRESENCE_ONLINE          MessageType = 320
	MessageType_PRESENCE_OFFLINE         MessageType = 321
	MessageType_FRIEND_REMOVED           MessageType = 322
	MessageType_BLOCK_NOTIFY             MessageType = 323
	MessageType_INVITE_ROOM              MessageType = 336
	MessageType_INVITE_ROOM_ACK          MessageType = 337
	MessageType_ERROR                    MessageType = 65535
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0:     "MESSAGE_TYPE_UNSPECIFIED",
		1:     "AUTH",
		2:     "AUTH_OK",
		3:     "AUTH_REJECTED",
		16:    "HEARTBEAT",
		17:    "HEARTBEAT_ACK",
		256:   "JOIN_ROOM",
		257:   "JOIN_ROOM_OK",
		258:   "LEAVE_ROOM",
		259:   "LEAVE_ROOM_OK",
		272:   "SEND_MSG",
		273:   "RECV_MSG",
		274:   "MSG_REJECTED",
		320:   "PRESENCE_ONLINE",
		321:   "PRESENCE_OFFLINE",
		322:   "FRIEND_REMOVED",
		323:   "BLOCK_NOTIFY",
		336:   "INVITE_ROOM",
		337:   "INVITE_ROOM_ACK",
		65535: "ERROR",
	}
	MessageType_value = map[string]int32{
		"MESSAGE_TYPE_UNSPECIFIED": 0,
		"AUTH":                     1,
		"AUTH_OK":                  2,
		"AUTH_REJECTED":            3,
		"HEARTBEAT":                16,
		"HEARTBEAT_ACK":            17,
		"JOIN_ROOM":                256,
		"JOIN_ROOM_OK":             257,
		"LEAVE_ROOM":               258,
		"LEAVE_ROOM_OK":            259,
		"SEND_MSG":                 272,
		"RECV_MSG":                 273,
		"MSG_REJECTED":             274,
		"PRESENCE_ONLINE":          320,
		"PRESENCE_OFFLINE":         321,
		"FRIEND_REMOVED":           322,
		"BLOCK_NOTIFY":             323,
		"INVITE_ROOM":              336,
		"INVITE_ROOM_ACK":          337,
		"ERROR":                    65535,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_chat_v1_chat_proto_enumTypes[0].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_chat_v1_chat_proto_enumTypes[0]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_chat_v1_chat_proto_rawDescGZIP(), []int{0}
}

type AuthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthRequest) Reset() {
	*x = AuthRequest{}
	mi := &file_chat_v1_chat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthRequest) ProtoMessage() {}

func (x *AuthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_v1_chat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthRequest.ProtoReflect.Descriptor instead.
func (*AuthRequest) Descriptor() ([]byte, []int) {
	return file_chat_v1_chat_proto_rawDescGZIP(), []int{0}
}

func (x *AuthRequest) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

type AuthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthResponse) Reset() {
	*x = AuthResponse{}
	mi := &file_chat_v1_chat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthResponse) ProtoMessage() {}

func (x *AuthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chat_v1_chat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthResponse.ProtoReflect.Descriptor instead.
func (*AuthResponse) Descriptor() ([]byte, []int) {
	return file_chat_v1_chat_proto_rawDescGZIP(), []int{1}
}

func (x *AuthResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AuthResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_chat_v1_chat_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_chat_v1_chat_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_chat_v1_chat_proto_rawDescGZIP(), []int{2}
}

type HeartbeatAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatAck) Reset() {
	*x = HeartbeatAck{}
	mi := &file_chat_v1_chat_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatAck) ProtoMessage() {}

func (x *HeartbeatAck) ProtoReflect() protoreflect.Message {
	mi := &file_chat_v1_chat_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatAck.ProtoReflect.Descriptor instead.
func (*HeartbeatAck) Descriptor() ([]byte, []int) {
	return file_chat_v1_chat_proto_rawDescGZIP(), []int{3}
}

type JoinRoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinRoomRequest) Reset() {
	*x = JoinRoomRequest{}
	mi := &file_chat_v1_chat_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRoomRequest) ProtoMessage() {}

func (x *JoinRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_v1_chat_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRoomRequest.ProtoReflect.Descriptor instead.
func (*JoinRoomRequest) Descriptor() ([]byte, []int) {
	return file_chat_v1_chat_proto_rawDescGZIP(), []int{4}
}

func (x *JoinRoomRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

type JoinRoomResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinRoomResponse) Reset() {
	*x = JoinRoomResponse{}
	mi := &file_chat_v1_chat_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinRoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRoomResponse) ProtoMessage() {}

func (x *JoinRoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chat_v1_chat_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRoomResponse.ProtoReflect.Descriptor instead.
func (*JoinRoomResponse) Descriptor() ([]byte, []int) {
	return file_chat_v1_chat_proto_rawDescGZIP(), []int{5}
}

func (x *JoinRoomResponse) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

type LeaveRoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveRoomRequest) Reset() {
	*x = LeaveRoomRequest{}
	mi := &file_chat_v1_chat_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveRoomRequest) ProtoMessage() {}

func (x *LeaveRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_v1_chat_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveRoomRequest.ProtoReflect.Descriptor instead.
func (*LeaveRoomRequest) Descriptor() ([]byte, []int) {
	return file_chat_v1_chat_proto_rawDescGZIP(), []int{6}
}

func (x *LeaveRoomRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

type LeaveRoomResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveRoomResponse) Reset() {
	*x = LeaveRoomResponse{}
	mi := &file_chat_v1_chat_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveRoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveRoomResponse) ProtoMessage() {}

func (x *LeaveRoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chat_v1_chat_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveRoomResponse.ProtoReflect.Descriptor instead.
func (*LeaveRoomResponse) Descriptor() ([]byte, []int) {
	return file_chat_v1_chat_proto_rawDescGZIP(), []int{7}
}

func (x *LeaveRoomResponse) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

type SendMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageRequest) Reset() {
	*x = SendMessageRequest{}
	mi := &file_chat_v1_chat_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageRequest) ProtoMessage() {}

func (x *SendMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_v1_chat_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageRequest.ProtoReflect.Descriptor instead.
func (*SendMessageRequest) Descriptor() ([]byte, []int) {
	return file_chat_v1_chat_proto_rawDescGZIP(), []int{8}
}

func (x *SendMessageRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *SendMessageRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *SendMessageRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type ReceiveMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	SenderId      string                 `protobuf:"bytes,2,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Timestamp     int64                  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	MessageId     string                 `protobuf:"bytes,6,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReceiveMessage) Reset() {
	*x = ReceiveMessage{}
	mi := &file_chat_v1_chat_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReceiveMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReceiveMessage) ProtoMessage() {}

func (x *ReceiveMessage) ProtoReflect() protoreflect.Message {
	mi := &file_chat_v1_chat_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReceiveMessage.ProtoReflect.Descriptor instead.
func (*ReceiveMessage) Descriptor() ([]byte, []int) {
	return file_chat_v1_chat_proto_rawDescGZIP(), []int{9}
}

func (x *ReceiveMessage) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *ReceiveMessage) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *ReceiveMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ReceiveMessage) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ReceiveMessage) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *ReceiveMessage) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

type ErrorMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorMessage) Reset() {
	*x = ErrorMessage{}
	mi := &file_chat_v1_chat_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorMessage) ProtoMessage() {}

func (x *ErrorMessage) ProtoReflect() protoreflect.Message {
	mi := &file_chat_v1_chat_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorMessage.ProtoReflect.Descriptor instead.
func (*ErrorMessage) Descriptor() ([]byte, []int) {
	return file_chat_v1_chat_proto_rawDescGZIP(), []int{10}
}

func (x *ErrorMessage) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ErrorMessage) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type PresenceOnline struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PresenceOnline) Reset() {
	*x = PresenceOnline{}
	mi := &file_chat_v1_chat_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PresenceOnline) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PresenceOnline) ProtoMessage() {}

func (x *PresenceOnline) ProtoReflect() protoreflect.Message {
	mi := &file_chat_v1_chat_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PresenceOnline.ProtoReflect.Descriptor instead.
func (*PresenceOnline) Descriptor() ([]byte, []int) {
	return file_chat_v1_chat_proto_rawDescGZIP(), []int{11}
}

func (x *PresenceOnline) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *PresenceOnline) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *PresenceOnline) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type PresenceOffline struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PresenceOffline) Reset() {
	*x = PresenceOffline{}
	mi := &file_chat_v1_chat_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PresenceOffline) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PresenceOffline) ProtoMessage() {}

func (x *PresenceOffline) ProtoReflect() protoreflect.Message {
	mi := &file_chat_v1_chat_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PresenceOffline.ProtoReflect.Descriptor instead.
func (*PresenceOffline) Descriptor() ([]byte, []int) {
	return file_chat_v1_chat_proto_rawDescGZIP(), []int{12}
}

func (x *PresenceOffline) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type FriendRemoved struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FriendRemoved) Reset() {
	*x = FriendRemoved{}
	mi := &file_chat_v1_chat_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FriendRemoved) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendRemoved) ProtoMessage() {}

func (x *FriendRemoved) ProtoReflect() protoreflect.Message {
	mi := &file_chat_v1_chat_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendRemoved.ProtoReflect.Descriptor instead.
func (*FriendRemoved) Descriptor() ([]byte, []int) {
	return file_chat_v1_chat_proto_rawDescGZIP(), []int{13}
}

func (x *FriendRemoved) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type BlockNotify struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BlockerId     string                 `protobuf:"bytes,1,opt,name=blocker_id,json=blockerId,proto3" json:"blocker_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockNotify) Reset() {
	*x = BlockNotify{}
	mi := &file_chat_v1_chat_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockNotify) ProtoMessage() {}

func (x *BlockNotify) ProtoReflect() protoreflect.Message {
	mi := &file_chat_v1_chat_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockNotify.ProtoReflect.Descriptor instead.
func (*BlockNotify) Descriptor() ([]byte, []int) {
	return file_chat_v1_chat_proto_rawDescGZIP(), []int{14}
}

func (x *BlockNotify) GetBlockerId() string {
	if x != nil {
		return x.BlockerId
	}
	return ""
}

type InviteRoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	TargetUserId  string                 `protobuf:"bytes,2,opt,name=target_user_id,json=targetUserId,proto3" json:"target_user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InviteRoomRequest) Reset() {
	*x = InviteRoomRequest{}
	mi := &file_chat_v1_chat_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InviteRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InviteRoomRequest) ProtoMessage() {}

func (x *InviteRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_v1_chat_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InviteRoomRequest.ProtoReflect.Descriptor instead.
func (*InviteRoomRequest) Descriptor() ([]byte, []int) {
	return file_chat_v1_chat_proto_rawDescGZIP(), []int{15}
}

func (x *InviteRoomRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *InviteRoomRequest) GetTargetUserId() string {
	if x != nil {
		return x.TargetUserId
	}
	return ""
}

type InviteRoomNotify struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RoomId          string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	InviterId       string                 `protobuf:"bytes,2,opt,name=inviter_id,json=inviterId,proto3" json:"inviter_id,omitempty"`
	InviterUsername string                 `protobuf:"bytes,3,opt,name=inviter_username,json=inviterUsername,proto3" json:"inviter_username,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *InviteRoomNotify) Reset() {
	*x = InviteRoomNotify{}
	mi := &file_chat_v1_chat_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InviteRoomNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InviteRoomNotify) ProtoMessage() {}

func (x *InviteRoomNotify) ProtoReflect() protoreflect.Message {
	mi := &file_chat_v1_chat_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InviteRoomNotify.ProtoReflect.Descriptor instead.
func (*InviteRoomNotify) Descriptor() ([]byte, []int) {
	return file_chat_v1_chat_proto_rawDescGZIP(), []int{16}
}

func (x *InviteRoomNotify) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *InviteRoomNotify) GetInviterId() string {
	if x != nil {
		return x.InviterId
	}
	return ""
}

func (x *InviteRoomNotify) GetInviterUsername() string {
	if x != nil {
		return x.InviterUsername
	}
	return ""
}

type InviteRoomAccept struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InviteRoomAccept) Reset() {
	*x = InviteRoomAccept{}
	mi := &file_chat_v1_chat_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InviteRoomAccept) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InviteRoomAccept) ProtoMessage() {}

func (x *InviteRoomAccept) ProtoReflect() protoreflect.Message {
	mi := &file_chat_v1_chat_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InviteRoomAccept.ProtoReflect.Descriptor instead.
func (*InviteRoomAccept) Descriptor() ([]byte, []int) {
	return file_chat_v1_chat_proto_rawDescGZIP(), []int{17}
}

func (x *InviteRoomAccept) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

type InviteRoomReject struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InviteRoomReject) Reset() {
	*x = InviteRoomReject{}
	mi := &file_chat_v1_chat_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InviteRoomReject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InviteRoomReject) ProtoMessage() {}

func (x *InviteRoomReject) ProtoReflect() protoreflect.Message {
	mi := &file_chat_v1_chat_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InviteRoomReject.ProtoReflect.Descriptor instead.
func (*InviteRoomReject) Descriptor() ([]byte, []int) {
	return file_chat_v1_chat_proto_rawDescGZIP(), []int{18}
}

func (x *InviteRoomReject) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

type ChatEnvelope struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Type     MessageType            `protobuf:"varint,1,opt,name=type,proto3,enum=chat.v1.MessageType" json:"type,omitempty"`
	Sequence uint32                 `protobuf:"varint,2,opt,name=sequence,proto3" json:"sequence,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ChatEnvelope_AuthRequest
	//	*ChatEnvelope_AuthResponse
	//	*ChatEnvelope_Heartbeat
	//	*ChatEnvelope_HeartbeatAck
	//	*ChatEnvelope_JoinRoomRequest
	//	*ChatEnvelope_JoinRoomResponse
	//	*ChatEnvelope_LeaveRoomRequest
	//	*ChatEnvelope_LeaveRoomResponse
	//	*ChatEnvelope_SendMessageRequest
	//	*ChatEnvelope_ReceiveMessage
	//	*ChatEnvelope_Error
	//	*ChatEnvelope_PresenceOnline
	//	*ChatEnvelope_PresenceOffline
	//	*ChatEnvelope_FriendRemoved
	//	*ChatEnvelope_BlockNotify
	//	*ChatEnvelope_InviteRoomRequest
	//	*ChatEnvelope_InviteRoomNotify
	//	*ChatEnvelope_InviteRoomAccept
	//	*ChatEnvelope_InviteRoomReject
	Payload       isChatEnvelope_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatEnvelope) Reset() {
	*x = ChatEnvelope{}
	mi := &file_chat_v1_chat_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatEnvelope) ProtoMessage() {}

func (x *ChatEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_chat_v1_chat_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatEnvelope.ProtoReflect.Descriptor instead.
func (*ChatEnvelope) Descriptor() ([]byte, []int) {
	return file_chat_v1_chat_proto_rawDescGZIP(), []int{19}
}

func (x *ChatEnvelope) GetType() MessageType {
	if x != nil {
		return x.Type
	}
	return MessageType_MESSAGE_TYPE_UNSPECIFIED
}

func (x *ChatEnvelope) GetSequence() uint32 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *ChatEnvelope) GetPayload() isChatEnvelope_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ChatEnvelope) GetAuthRequest() *AuthRequest {
	if x != nil {
		if x, ok := x.Payload.(*ChatEnvelope_AuthRequest); ok {
			return x.AuthRequest
		}
	}
	return nil
}

func (x *ChatEnvelope) GetAuthResponse() *AuthResponse {
	if x != nil {
		if x, ok := x.Payload.(*ChatEnvelope_AuthResponse); ok {
			return x.AuthResponse
		}
	}
	return nil
}

func (x *ChatEnvelope) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Payload.(*ChatEnvelope_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *ChatEnvelope) GetHeartbeatAck() *HeartbeatAck {
	if x != nil {
		if x, ok := x.Payload.(*ChatEnvelope_HeartbeatAck); ok {
			return x.HeartbeatAck
		}
	}
	return nil
}

func (x *ChatEnvelope) GetJoinRoomRequest() *JoinRoomRequest {
	if x != nil {
		if x, ok := x.Payload.(*ChatEnvelope_JoinRoomRequest); ok {
			return x.JoinRoomRequest
		}
	}
	return nil
}

func (x *ChatEnvelope) GetJoinRoomResponse() *JoinRoomResponse {
	if x != nil {
		if x, ok := x.Payload.(*ChatEnvelope_JoinRoomResponse); ok {
			return x.JoinRoomResponse
		}
	}
	return nil
}

func (x *ChatEnvelope) GetLeaveRoomRequest() *LeaveRoomRequest {
	if x != nil {
		if x, ok := x.Payload.(*ChatEnvelope_LeaveRoomRequest); ok {
			return x.LeaveRoomRequest
		}
	}
	return nil
}

func (x *ChatEnvelope) GetLeaveRoomResponse() *LeaveRoomResponse {
	if x != nil {
		if x, ok := x.Payload.(*ChatEnvelope_LeaveRoomResponse); ok {
			return x.LeaveRoomResponse
		}
	}
	return nil
}

func (x *ChatEnvelope) GetSendMessageRequest() *SendMessageRequest {
	if x != nil {
		if x, ok := x.Payload.(*ChatEnvelope_SendMessageRequest); ok {
			return x.SendMessageRequest
		}
	}
	return nil
}

func (x *ChatEnvelope) GetReceiveMessage() *ReceiveMessage {
	if x != nil {
		if x, ok := x.Payload.(*ChatEnvelope_ReceiveMessage); ok {
			return x.ReceiveMessage
		}
	}
	return nil
}

func (x *ChatEnvelope) GetError() *ErrorMessage {
	if x != nil {
		if x, ok := x.Payload.(*ChatEnvelope_Error); ok {
			return x.Error
		}
	}
	return nil
}

func (x *ChatEnvelope) GetPresenceOnline() *PresenceOnline {
	if x != nil {
		if x, ok := x.Payload.(*ChatEnvelope_PresenceOnline); ok {
			return x.PresenceOnline
		}
	}
	return nil
}

func (x *ChatEnvelope) GetPresenceOffline() *PresenceOffline {
	if x != nil {
		if x, ok := x.Payload.(*ChatEnvelope_PresenceOffline); ok {
			return x.PresenceOffline
		}
	}
	return nil
}

func (x *ChatEnvelope) GetFriendRemoved() *FriendRemoved {
	if x != nil {
		if x, ok := x.Payload.(*ChatEnvelope_FriendRemoved); ok {
			return x.FriendRemoved
		}
	}
	return nil
}

func (x *ChatEnvelope) GetBlockNotify() *BlockNotify {
	if x != nil {
		if x, ok := x.Payload.(*ChatEnvelope_BlockNotify); ok {
			return x.BlockNotify
		}
	}
	return nil
}

func (x *ChatEnvelope) GetInviteRoomRequest() *InviteRoomRequest {
	if x != nil {
		if x, ok := x.Payload.(*ChatEnvelope_InviteRoomRequest); ok {
			return x.InviteRoomRequest
		}
	}
	return nil
}

func (x *ChatEnvelope) GetInviteRoomNotify() *InviteRoomNotify {
	if x != nil {
		if x, ok := x.Payload.(*ChatEnvelope_InviteRoomNotify); ok {
			return x.InviteRoomNotify
		}
	}
	return nil
}

func (x *ChatEnvelope) GetInviteRoomAccept() *InviteRoomAccept {
	if x != nil {
		if x, ok := x.Payload.(*ChatEnvelope_InviteRoomAccept); ok {
			return x.InviteRoomAccept
		}
	}
	return nil
}

func (x *ChatEnvelope) GetInviteRoomReject() *InviteRoomReject {
	if x != nil {
		if x, ok := x.Payload.(*ChatEnvelope_InviteRoomReject); ok {
			return x.InviteRoomReject
		}
	}
	return nil
}

type isChatEnvelope_Payload interface {
	isChatEnvelope_Payload()
}

type ChatEnvelope_AuthRequest struct {
	AuthRequest *AuthRequest `protobuf:"bytes,10,opt,name=auth_request,json=authRequest,proto3,oneof"`
}

type ChatEnvelope_AuthResponse struct {
	AuthResponse *AuthResponse `protobuf:"bytes,11,opt,name=auth_response,json=authResponse,proto3,oneof"`
}

type ChatEnvelope_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,12,opt,name=heartbeat,proto3,oneof"`
}

type ChatEnvelope_HeartbeatAck struct {
	HeartbeatAck *HeartbeatAck `protobuf:"bytes,13,opt,name=heartbeat_ack,json=heartbeatAck,proto3,oneof"`
}

type ChatEnvelope_JoinRoomRequest struct {
	JoinRoomRequest *JoinRoomRequest `protobuf:"bytes,20,opt,name=join_room_request,json=joinRoomRequest,proto3,oneof"`
}

type ChatEnvelope_JoinRoomResponse struct {
	JoinRoomResponse *JoinRoomResponse `protobuf:"bytes,21,opt,name=join_room_response,json=joinRoomResponse,proto3,oneof"`
}

type ChatEnvelope_LeaveRoomRequest struct {
	LeaveRoomRequest *LeaveRoomRequest `protobuf:"bytes,22,opt,name=leave_room_request,json=leaveRoomRequest,proto3,oneof"`
}

type ChatEnvelope_LeaveRoomResponse struct {
	LeaveRoomResponse *LeaveRoomResponse `protobuf:"bytes,23,opt,name=leave_room_response,json=leaveRoomResponse,proto3,oneof"`
}

type ChatEnvelope_SendMessageRequest struct {
	SendMessageRequest *SendMessageRequest `protobuf:"bytes,30,opt,name=send_message_request,json=sendMessageRequest,proto3,oneof"`
}

type ChatEnvelope_ReceiveMessage struct {
	ReceiveMessage *ReceiveMessage `protobuf:"bytes,31,opt,name=receive_message,json=receiveMessage,proto3,oneof"`
}

type ChatEnvelope_Error struct {
	Error *ErrorMessage `protobuf:"bytes,50,opt,name=error,proto3,oneof"`
}

type ChatEnvelope_PresenceOnline struct {
	PresenceOnline *PresenceOnline `protobuf:"bytes,40,opt,name=presence_online,json=presenceOnline,proto3,oneof"`
}

type ChatEnvelope_PresenceOffline struct {
	PresenceOffline *PresenceOffline `protobuf:"bytes,41,opt,name=presence_offline,json=presenceOffline,proto3,oneof"`
}

type ChatEnvelope_FriendRemoved struct {
	FriendRemoved *FriendRemoved `protobuf:"bytes,42,opt,name=friend_removed,json=friendRemoved,proto3,oneof"`
}

type ChatEnvelope_BlockNotify struct {
	BlockNotify *BlockNotify `protobuf:"bytes,43,opt,name=block_notify,json=blockNotify,proto3,oneof"`
}

type ChatEnvelope_InviteRoomRequest struct {
	InviteRoomRequest *InviteRoomRequest `protobuf:"bytes,60,opt,name=invite_room_request,json=inviteRoomRequest,proto3,oneof"`
}

type ChatEnvelope_InviteRoomNotify struct {
	InviteRoomNotify *InviteRoomNotify `protobuf:"bytes,61,opt,name=invite_room_notify,json=inviteRoomNotify,proto3,oneof"`
}

type ChatEnvelope_InviteRoomAccept struct {
	InviteRoomAccept *InviteRoomAccept `protobuf:"bytes,62,opt,name=invite_room_accept,json=inviteRoomAccept,proto3,oneof"`
}

type ChatEnvelope_InviteRoomReject struct {
	InviteRoomReject *InviteRoomReject `protobuf:"bytes,63,opt,name=invite_room_reject,json=inviteRoomReject,proto3,oneof"`
}

func (*ChatEnvelope_AuthRequest) isChatEnvelope_Payload() {}

func (*ChatEnvelope_AuthResponse) isChatEnvelope_Payload() {}

func (*ChatEnvelope_Heartbeat) isChatEnvelope_Payload() {}

func (*ChatEnvelope_HeartbeatAck) isChatEnvelope_Payload() {}

func (*ChatEnvelope_JoinRoomRequest) isChatEnvelope_Payload() {}

func (*ChatEnvelope_JoinRoomResponse) isChatEnvelope_Payload() {}

func (*ChatEnvelope_LeaveRoomRequest) isChatEnvelope_Payload() {}

func (*ChatEnvelope_LeaveRoomResponse) isChatEnvelope_Payload() {}

func (*ChatEnvelope_SendMessageRequest) isChatEnvelope_Payload() {}

func (*ChatEnvelope_ReceiveMessage) isChatEnvelope_Payload() {}

func (*ChatEnvelope_Error) isChatEnvelope_Payload() {}

func (*ChatEnvelope_PresenceOnline) isChatEnvelope_Payload() {}

func (*ChatEnvelope_PresenceOffline) isChatEnvelope_Payload() {}

func (*ChatEnvelope_FriendRemoved) isChatEnvelope_Payload() {}

func (*ChatEnvelope_BlockNotify) isChatEnvelope_Payload() {}

func (*ChatEnvelope_InviteRoomRequest) isChatEnvelope_Payload() {}

func (*ChatEnvelope_InviteRoomNotify) isChatEnvelope_Payload() {}

func (*ChatEnvelope_InviteRoomAccept) isChatEnvelope_Payload() {}

func (*ChatEnvelope_InviteRoomReject) isChatEnvelope_Payload() {}

var File_chat_v1_chat_proto protoreflect.FileDescriptor

const file_chat_v1_chat_proto_rawDesc = "" +
	"\n" +
	"\x12chat/v1/chat.proto\x12\achat.v1\"0\n" +
	"\vAuthRequest\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\"F\n" +
	"\fAuthResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\"\v\n" +
	"\tHeartbeat\"\x0e\n" +
	"\fHeartbeatAck\"*\n" +
	"\x0fJoinRoomRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\"+\n" +
	"\x10JoinRoomResponse\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\"+\n" +
	"\x10LeaveRoomRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\",\n" +
	"\x11LeaveRoomResponse\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\"[\n" +
	"\x12SendMessageRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\"\xb1\x01\n" +
	"\x0eReceiveMessage\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x1b\n" +
	"\tsender_id\x18\x02 \x01(\tR\bsenderId\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\x12\x1d\n" +
	"\n" +
	"message_id\x18\x06 \x01(\tR\tmessageId\"<\n" +
	"\fErrorMessage\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"]\n" +
	"\x0ePresenceOnline\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\"*\n" +
	"\x0fPresenceOffline\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"(\n" +
	"\rFriendRemoved\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\",\n" +
	"\vBlockNotify\x12\x1d\n" +
	"\n" +
	"blocker_id\x18\x01 \x01(\tR\tblockerId\"R\n" +
	"\x11InviteRoomRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12$\n" +
	"\x0etarget_user_id\x18\x02 \x01(\tR\ftargetUserId\"u\n" +
	"\x10InviteRoomNotify\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x1d\n" +
	"\n" +
	"inviter_id\x18\x02 \x01(\tR\tinviterId\x12)\n" +
	"\x10inviter_username\x18\x03 \x01(\tR\x0finviterUsername\"+\n" +
	"\x10InviteRoomAccept\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\"+\n" +
	"\x10InviteRoomReject\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\"\xf0\n" +
	"\n" +
	"\fChatEnvelope\x12(\n" +
	"\x04type\x18\x01 \x01(\x0e2\x14.chat.v1.MessageTypeR\x04type\x12\x1a\n" +
	"\bsequence\x18\x02 \x01(\rR\bsequence\x129\n" +
	"\fauth_request\x18\n" +
	" \x01(\v2\x14.chat.v1.AuthRequestH\x00R\vauthRequest\x12<\n" +
	"\rauth_response\x18\v \x01(\v2\x15.chat.v1.AuthResponseH\x00R\fauthResponse\x122\n" +
	"\theartbeat\x18\f \x01(\v2\x12.chat.v1.HeartbeatH\x00R\theartbeat\x12<\n" +
	"\rheartbeat_ack\x18\r \x01(\v2\x15.chat.v1.HeartbeatAckH\x00R\fheartbeatAck\x12F\n" +
	"\x11join_room_request\x18\x14 \x01(\v2\x18.chat.v1.JoinRoomRequestH\x00R\x0fjoinRoomRequest\x12I\n" +
	"\x12join_room_response\x18\x15 \x01(\v2\x19.chat.v1.JoinRoomResponseH\x00R\x10joinRoomResponse\x12I\n" +
	"\x12leave_room_request\x18\x16 \x01(\v2\x19.chat.v1.LeaveRoomRequestH\x00R\x10leaveRoomRequest\x12L\n" +
	"\x13leave_room_response\x18\x17 \x01(\v2\x1a.chat.v1.LeaveRoomResponseH\x00R\x11leaveRoomResponse\x12O\n" +
	"\x14send_message_request\x18\x1e \x01(\v2\x1b.chat.v1.SendMessageRequestH\x00R\x12sendMessageRequest\x12B\n" +
	"\x0freceive_message\x18\x1f \x01(\v2\x17.chat.v1.ReceiveMessageH\x00R\x0ereceiveMessage\x12-\n" +
	"\x05error\x182 \x01(\v2\x15.chat.v1.ErrorMessageH\x00R\x05error\x12B\n" +
	"\x0fpresence_online\x18( \x01(\v2\x17.chat.v1.PresenceOnlineH\x00R\x0epresenceOnline\x12E\n" +
	"\x10presence_offline\x18) \x01(\v2\x18.chat.v1.PresenceOfflineH\x00R\x0fpresenceOffline\x12?\n" +
	"\x0efriend_removed\x18* \x01(\v2\x16.chat.v1.FriendRemovedH\x00R\rfriendRemoved\x129\n" +
	"\fblock_notify\x18+ \x01(\v2\x14.chat.v1.BlockNotifyH\x00R\vblockNotify\x12L\n" +
	"\x13invite_room_request\x18< \x01(\v2\x1a.chat.v1.InviteRoomRequestH\x00R\x11inviteRoomRequest\x12I\n" +
	"\x12invite_room_notify\x18= \x01(\v2\x19.chat.v1.InviteRoomNotifyH\x00R\x10inviteRoomNotify\x12I\n" +
	"\x12invite_room_accept\x18> \x01(\v2\x19.chat.v1.InviteRoomAcceptH\x00R\x10inviteRoomAccept\x12I\n" +
	"\x12invite_room_reject\x18? \x01(\v2\x19.chat.v1.InviteRoomRejectH\x00R\x10inviteRoomRejectB\t\n" +
	"\apayload*\xfa\x02\n" +
	"\vMessageType\x12\x1c\n" +
	"\x18MESSAGE_TYPE_UNSPECIFIED\x10\x00\x12\b\n" +
	"\x04AUTH\x10\x01\x12\v\n" +
	"\aAUTH_OK\x10\x02\x12\x11\n" +
	"\rAUTH_REJECTED\x10\x03\x12\r\n" +
	"\tHEARTBEAT\x10\x10\x12\x11\n" +
	"\rHEARTBEAT_ACK\x10\x11\x12\x0e\n" +
	"\tJOIN_ROOM\x10\x80\x02\x12\x11\n" +
	"\fJOIN_ROOM_OK\x10\x81\x02\x12\x0f\n" +
	"\n" +
	"LEAVE_ROOM\x10\x82\x02\x12\x12\n" +
	"\rLEAVE_ROOM_OK\x10\x83\x02\x12\r\n" +
	"\bSEND_MSG\x10\x90\x02\x12\r\n" +
	"\bRECV_MSG\x10\x91\x02\x12\x11\n" +
	"\fMSG_REJECTED\x10\x92\x02\x12\x14\n" +
	"\x0fPRESENCE_ONLINE\x10\xc0\x02\x12\x15\n" +
	"\x10PRESENCE_OFFLINE\x10\xc1\x02\x12\x13\n" +
	"\x0eFRIEND_REMOVED\x10\xc2\x02\x12\x11\n" +
	"\fBLOCK_NOTIFY\x10\xc3\x02\x12\x10\n" +
	"\vINVITE_ROOM\x10\xd0\x02\x12\x14\n" +
	"\x0fINVITE_ROOM_ACK\x10\xd1\x02\x12\v\n" +
	"\x05ERROR\x10\xff\xff\x03B\x8a\x01\n" +
	"\vcom.chat.v1B\tChatProtoP\x01Z3github.com/cyandie/backend/api/proto/chat/v1;chatv1\xa2\x02\x03CXX\xaa\x02\aChat.V1\xca\x02\aChat\\V1\xe2\x02\x13Chat\\V1\\GPBMetadata\xea\x02\bChat::V1b\x06proto3"

var (
	file_chat_v1_chat_proto_rawDescOnce sync.Once
	file_chat_v1_chat_proto_rawDescData []byte
)

func file_chat_v1_chat_proto_rawDescGZIP() []byte {
	file_chat_v1_chat_proto_rawDescOnce.Do(func() {
		file_chat_v1_chat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chat_v1_chat_proto_rawDesc), len(file_chat_v1_chat_proto_rawDesc)))
	})
	return file_chat_v1_chat_proto_rawDescData
}

var file_chat_v1_chat_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_chat_v1_chat_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_chat_v1_chat_proto_goTypes = []any{
	(MessageType)(0),           // 0: chat.v1.MessageType
	(*AuthRequest)(nil),        // 1: chat.v1.AuthRequest
	(*AuthResponse)(nil),       // 2: chat.v1.AuthResponse
	(*Heartbeat)(nil),          // 3: chat.v1.Heartbeat
	(*HeartbeatAck)(nil),       // 4: chat.v1.HeartbeatAck
	(*JoinRoomRequest)(nil),    // 5: chat.v1.JoinRoomRequest
	(*JoinRoomResponse)(nil),   // 6: chat.v1.JoinRoomResponse
	(*LeaveRoomRequest)(nil),   // 7: chat.v1.LeaveRoomRequest
	(*LeaveRoomResponse)(nil),  // 8: chat.v1.LeaveRoomResponse
	(*SendMessageRequest)(nil), // 9: chat.v1.SendMessageRequest
	(*ReceiveMessage)(nil),     // 10: chat.v1.ReceiveMessage
	(*ErrorMessage)(nil),       // 11: chat.v1.ErrorMessage
	(*PresenceOnline)(nil),     // 12: chat.v1.PresenceOnline
	(*PresenceOffline)(nil),    // 13: chat.v1.PresenceOffline
	(*FriendRemoved)(nil),      // 14: chat.v1.FriendRemoved
	(*BlockNotify)(nil),        // 15: chat.v1.BlockNotify
	(*InviteRoomRequest)(nil),  // 16: chat.v1.InviteRoomRequest
	(*InviteRoomNotify)(nil),   // 17: chat.v1.InviteRoomNotify
	(*InviteRoomAccept)(nil),   // 18: chat.v1.InviteRoomAccept
	(*InviteRoomReject)(nil),   // 19: chat.v1.InviteRoomReject
	(*ChatEnvelope)(nil),       // 20: chat.v1.ChatEnvelope
}
var file_chat_v1_chat_proto_depIdxs = []int32{
	0,  // 0: chat.v1.ChatEnvelope.type:type_name -> chat.v1.MessageType
	1,  // 1: chat.v1.ChatEnvelope.auth_request:type_name -> chat.v1.AuthRequest
	2,  // 2: chat.v1.ChatEnvelope.auth_response:type_name -> chat.v1.AuthResponse
	3,  // 3: chat.v1.ChatEnvelope.heartbeat:type_name -> chat.v1.Heartbeat
	4,  // 4: chat.v1.ChatEnvelope.heartbeat_ack:type_name -> chat.v1.HeartbeatAck
	5,  // 5: chat.v1.ChatEnvelope.join_room_request:type_name -> chat.v1.JoinRoomRequest
	6,  // 6: chat.v1.ChatEnvelope.join_room_response:type_name -> chat.v1.JoinRoomResponse
	7,  // 7: chat.v1.ChatEnvelope.leave_room_request:type_name -> chat.v1.LeaveRoomRequest
	8,  // 8: chat.v1.ChatEnvelope.leave_room_response:type_name -> chat.v1.LeaveRoomResponse
	9,  // 9: chat.v1.ChatEnvelope.send_message_request:type_name -> chat.v1.SendMessageRequest
	10, // 10: chat.v1.ChatEnvelope.receive_message:type_name -> chat.v1.ReceiveMessage
	11, // 11: chat.v1.ChatEnvelope.error:type_name -> chat.v1.ErrorMessage
	12, // 12: chat.v1.ChatEnvelope.presence_online:type_name -> chat.v1.PresenceOnline
	13, // 13: chat.v1.ChatEnvelope.presence_offline:type_name -> chat.v1.PresenceOffline
	14, // 14: chat.v1.ChatEnvelope.friend_removed:type_name -> chat.v1.FriendRemoved
	15, // 15: chat.v1.ChatEnvelope.block_notify:type_name -> chat.v1.BlockNotify
	16, // 16: chat.v1.ChatEnvelope.invite_room_request:type_name -> chat.v1.InviteRoomRequest
	17, // 17: chat.v1.ChatEnvelope.invite_room_notify:type_name -> chat.v1.InviteRoomNotify
	18, // 18: chat.v1.ChatEnvelope.invite_room_accept:type_name -> chat.v1.InviteRoomAccept
	19, // 19: chat.v1.ChatEnvelope.invite_room_reject:type_name -> chat.v1.InviteRoomReject
	20, // [20:20] is the sub-list for method output_type
	20, // [20:20] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_chat_v1_chat_proto_init() }
func file_chat_v1_chat_proto_init() {
	if File_chat_v1_chat_proto != nil {
		return
	}
	file_chat_v1_chat_proto_msgTypes[19].OneofWrappers = []any{
		(*ChatEnvelope_AuthRequest)(nil),
		(*ChatEnvelope_AuthResponse)(nil),
		(*ChatEnvelope_Heartbeat)(nil),
		(*ChatEnvelope_HeartbeatAck)(nil),
		(*ChatEnvelope_JoinRoomRequest)(nil),
		(*ChatEnvelope_JoinRoomResponse)(nil),
		(*ChatEnvelope_LeaveRoomRequest)(nil),
		(*ChatEnvelope_LeaveRoomResponse)(nil),
		(*ChatEnvelope_SendMessageRequest)(nil),
		(*ChatEnvelope_ReceiveMessage)(nil),
		(*ChatEnvelope_Error)(nil),
		(*ChatEnvelope_PresenceOnline)(nil),
		(*ChatEnvelope_PresenceOffline)(nil),
		(*ChatEnvelope_FriendRemoved)(nil),
		(*ChatEnvelope_BlockNotify)(nil),
		(*ChatEnvelope_InviteRoomRequest)(nil),
		(*ChatEnvelope_InviteRoomNotify)(nil),
		(*ChatEnvelope_InviteRoomAccept)(nil),
		(*ChatEnvelope_InviteRoomReject)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chat_v1_chat_proto_rawDesc), len(file_chat_v1_chat_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_chat_v1_chat_proto_goTypes,
		DependencyIndexes: file_chat_v1_chat_proto_depIdxs,
		EnumInfos:         file_chat_v1_chat_proto_enumTypes,
		MessageInfos:      file_chat_v1_chat_proto_msgTypes,
	}.Build()
	File_chat_v1_chat_proto = out.File
	file_chat_v1_chat_proto_goTypes = nil
	file_chat_v1_chat_proto_depIdxs = nil
}
