// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: admin.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const createAdminUser = `-- name: CreateAdminUser :one
INSERT INTO admin_users (username, password_hash, role)
VALUES ($1, $2, $3)
RETURNING id, username, password_hash, role, status, created_at, updated_at
`

type CreateAdminUserParams struct {
	Username     string `json:"username"`
	PasswordHash string `json:"password_hash"`
	Role         string `json:"role"`
}

func (q *Queries) CreateAdminUser(ctx context.Context, arg CreateAdminUserParams) (AdminUser, error) {
	row := q.db.QueryRowContext(ctx, createAdminUser, arg.Username, arg.PasswordHash, arg.Role)
	var i AdminUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Role,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createAuditLog = `-- name: CreateAuditLog :one
INSERT INTO audit_logs (operator_id, action, target_type, target_id, before_value, after_value, reason, ip)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, operator_id, action, target_type, target_id, before_value, after_value, reason, ip, created_at
`

type CreateAuditLogParams struct {
	OperatorID  uuid.NullUUID         `json:"operator_id"`
	Action      string                `json:"action"`
	TargetType  string                `json:"target_type"`
	TargetID    string                `json:"target_id"`
	BeforeValue pqtype.NullRawMessage `json:"before_value"`
	AfterValue  pqtype.NullRawMessage `json:"after_value"`
	Reason      sql.NullString        `json:"reason"`
	Ip          sql.NullString        `json:"ip"`
}

func (q *Queries) CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (AuditLog, error) {
	row := q.db.QueryRowContext(ctx, createAuditLog,
		arg.OperatorID,
		arg.Action,
		arg.TargetType,
		arg.TargetID,
		arg.BeforeValue,
		arg.AfterValue,
		arg.Reason,
		arg.Ip,
	)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.OperatorID,
		&i.Action,
		&i.TargetType,
		&i.TargetID,
		&i.BeforeValue,
		&i.AfterValue,
		&i.Reason,
		&i.Ip,
		&i.CreatedAt,
	)
	return i, err
}

const getAdminByUsername = `-- name: GetAdminByUsername :one
SELECT id, username, password_hash, role, status, created_at, updated_at FROM admin_users WHERE username = $1
`

func (q *Queries) GetAdminByUsername(ctx context.Context, username string) (AdminUser, error) {
	row := q.db.QueryRowContext(ctx, getAdminByUsername, username)
	var i AdminUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Role,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAuditLogs = `-- name: ListAuditLogs :many
SELECT id, operator_id, action, target_type, target_id, before_value, after_value, reason, ip, created_at FROM audit_logs ORDER BY created_at DESC LIMIT $1 OFFSET $2
`

type ListAuditLogsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]AuditLog, error) {
	rows, err := q.db.QueryContext(ctx, listAuditLogs, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.OperatorID,
			&i.Action,
			&i.TargetType,
			&i.TargetID,
			&i.BeforeValue,
			&i.AfterValue,
			&i.Reason,
			&i.Ip,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
