// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: chat.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const addRoomMember = `-- name: AddRoomMember :one
INSERT INTO chat_room_members (room_id, user_id, role)
VALUES ($1, $2, $3)
RETURNING id, room_id, user_id, role, joined_at
`

type AddRoomMemberParams struct {
	RoomID uuid.UUID `json:"room_id"`
	UserID uuid.UUID `json:"user_id"`
	Role   string    `json:"role"`
}

func (q *Queries) AddRoomMember(ctx context.Context, arg AddRoomMemberParams) (ChatRoomMember, error) {
	row := q.db.QueryRowContext(ctx, addRoomMember, arg.RoomID, arg.UserID, arg.Role)
	var i ChatRoomMember
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.UserID,
		&i.Role,
		&i.JoinedAt,
	)
	return i, err
}

const createChatMessage = `-- name: CreateChatMessage :one
INSERT INTO chat_messages (room_id, sender_id, content, type)
VALUES ($1, $2, $3, $4)
RETURNING id, room_id, sender_id, content, type, created_at
`

type CreateChatMessageParams struct {
	RoomID   uuid.UUID `json:"room_id"`
	SenderID uuid.UUID `json:"sender_id"`
	Content  string    `json:"content"`
	Type     string    `json:"type"`
}

func (q *Queries) CreateChatMessage(ctx context.Context, arg CreateChatMessageParams) (ChatMessage, error) {
	row := q.db.QueryRowContext(ctx, createChatMessage,
		arg.RoomID,
		arg.SenderID,
		arg.Content,
		arg.Type,
	)
	var i ChatMessage
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.SenderID,
		&i.Content,
		&i.Type,
		&i.CreatedAt,
	)
	return i, err
}

const createChatRoom = `-- name: CreateChatRoom :one
INSERT INTO chat_rooms (type, name, metadata)
VALUES ($1, $2, $3)
RETURNING id, type, name, metadata, created_at
`

type CreateChatRoomParams struct {
	Type     string                `json:"type"`
	Name     sql.NullString        `json:"name"`
	Metadata pqtype.NullRawMessage `json:"metadata"`
}

func (q *Queries) CreateChatRoom(ctx context.Context, arg CreateChatRoomParams) (ChatRoom, error) {
	row := q.db.QueryRowContext(ctx, createChatRoom, arg.Type, arg.Name, arg.Metadata)
	var i ChatRoom
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Name,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const getChatMessages = `-- name: GetChatMessages :many
SELECT id, room_id, sender_id, content, type, created_at FROM chat_messages
WHERE room_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type GetChatMessagesParams struct {
	RoomID uuid.UUID `json:"room_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

func (q *Queries) GetChatMessages(ctx context.Context, arg GetChatMessagesParams) ([]ChatMessage, error) {
	rows, err := q.db.QueryContext(ctx, getChatMessages, arg.RoomID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChatMessage{}
	for rows.Next() {
		var i ChatMessage
		if err := rows.Scan(
			&i.ID,
			&i.RoomID,
			&i.SenderID,
			&i.Content,
			&i.Type,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getChatRoom = `-- name: GetChatRoom :one
SELECT id, type, name, metadata, created_at FROM chat_rooms WHERE id = $1
`

func (q *Queries) GetChatRoom(ctx context.Context, id uuid.UUID) (ChatRoom, error) {
	row := q.db.QueryRowContext(ctx, getChatRoom, id)
	var i ChatRoom
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Name,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const getRoomMembers = `-- name: GetRoomMembers :many
SELECT id, room_id, user_id, role, joined_at FROM chat_room_members WHERE room_id = $1
`

func (q *Queries) GetRoomMembers(ctx context.Context, roomID uuid.UUID) ([]ChatRoomMember, error) {
	rows, err := q.db.QueryContext(ctx, getRoomMembers, roomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChatRoomMember{}
	for rows.Next() {
		var i ChatRoomMember
		if err := rows.Scan(
			&i.ID,
			&i.RoomID,
			&i.UserID,
			&i.Role,
			&i.JoinedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoomsByUser = `-- name: ListRoomsByUser :many
SELECT cr.id, cr.type, cr.name, cr.metadata, cr.created_at
FROM chat_rooms cr
JOIN chat_room_members crm ON cr.id = crm.room_id
WHERE crm.user_id = $1
ORDER BY cr.created_at DESC
`

func (q *Queries) ListRoomsByUser(ctx context.Context, userID uuid.UUID) ([]ChatRoom, error) {
	rows, err := q.db.QueryContext(ctx, listRoomsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChatRoom{}
	for rows.Next() {
		var i ChatRoom
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Name,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeRoomMember = `-- name: RemoveRoomMember :one
DELETE FROM chat_room_members WHERE room_id = $1 AND user_id = $2
RETURNING id, room_id, user_id, role, joined_at
`

type RemoveRoomMemberParams struct {
	RoomID uuid.UUID `json:"room_id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) RemoveRoomMember(ctx context.Context, arg RemoveRoomMemberParams) (ChatRoomMember, error) {
	row := q.db.QueryRowContext(ctx, removeRoomMember, arg.RoomID, arg.UserID)
	var i ChatRoomMember
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.UserID,
		&i.Role,
		&i.JoinedAt,
	)
	return i, err
}
