// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: credentials.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createCredential = `-- name: CreateCredential :one
INSERT INTO credentials (user_id, type, identifier, secret_hash, verified)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, type, identifier, secret_hash, verified, created_at
`

type CreateCredentialParams struct {
	UserID     uuid.UUID      `json:"user_id"`
	Type       string         `json:"type"`
	Identifier string         `json:"identifier"`
	SecretHash sql.NullString `json:"secret_hash"`
	Verified   bool           `json:"verified"`
}

func (q *Queries) CreateCredential(ctx context.Context, arg CreateCredentialParams) (Credential, error) {
	row := q.db.QueryRowContext(ctx, createCredential,
		arg.UserID,
		arg.Type,
		arg.Identifier,
		arg.SecretHash,
		arg.Verified,
	)
	var i Credential
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Identifier,
		&i.SecretHash,
		&i.Verified,
		&i.CreatedAt,
	)
	return i, err
}

const getCredentialByTypeIdentifier = `-- name: GetCredentialByTypeIdentifier :one
SELECT id, user_id, type, identifier, secret_hash, verified, created_at FROM credentials WHERE type = $1 AND identifier = $2
`

type GetCredentialByTypeIdentifierParams struct {
	Type       string `json:"type"`
	Identifier string `json:"identifier"`
}

func (q *Queries) GetCredentialByTypeIdentifier(ctx context.Context, arg GetCredentialByTypeIdentifierParams) (Credential, error) {
	row := q.db.QueryRowContext(ctx, getCredentialByTypeIdentifier, arg.Type, arg.Identifier)
	var i Credential
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Identifier,
		&i.SecretHash,
		&i.Verified,
		&i.CreatedAt,
	)
	return i, err
}

const getCredentialsByUserID = `-- name: GetCredentialsByUserID :many
SELECT id, user_id, type, identifier, secret_hash, verified, created_at FROM credentials WHERE user_id = $1
`

func (q *Queries) GetCredentialsByUserID(ctx context.Context, userID uuid.UUID) ([]Credential, error) {
	rows, err := q.db.QueryContext(ctx, getCredentialsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Credential{}
	for rows.Next() {
		var i Credential
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.Identifier,
			&i.SecretHash,
			&i.Verified,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
