// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: friends.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createFriendship = `-- name: CreateFriendship :one
INSERT INTO friendships (user_id, friend_id, status)
VALUES ($1, $2, $3)
RETURNING id, user_id, friend_id, status, created_at, updated_at
`

type CreateFriendshipParams struct {
	UserID   uuid.UUID `json:"user_id"`
	FriendID uuid.UUID `json:"friend_id"`
	Status   string    `json:"status"`
}

func (q *Queries) CreateFriendship(ctx context.Context, arg CreateFriendshipParams) (Friendship, error) {
	row := q.db.QueryRowContext(ctx, createFriendship, arg.UserID, arg.FriendID, arg.Status)
	var i Friendship
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FriendID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteFriendship = `-- name: DeleteFriendship :one
DELETE FROM friendships WHERE id = $1 RETURNING id, user_id, friend_id, status, created_at, updated_at
`

func (q *Queries) DeleteFriendship(ctx context.Context, id uuid.UUID) (Friendship, error) {
	row := q.db.QueryRowContext(ctx, deleteFriendship, id)
	var i Friendship
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FriendID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFriendship = `-- name: GetFriendship :one
SELECT id, user_id, friend_id, status, created_at, updated_at FROM friendships WHERE id = $1
`

func (q *Queries) GetFriendship(ctx context.Context, id uuid.UUID) (Friendship, error) {
	row := q.db.QueryRowContext(ctx, getFriendship, id)
	var i Friendship
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FriendID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listFriends = `-- name: ListFriends :many
SELECT id, user_id, friend_id, status, created_at, updated_at FROM friendships
WHERE (user_id = $1 OR friend_id = $1) AND status = 'accepted'
ORDER BY updated_at DESC
`

func (q *Queries) ListFriends(ctx context.Context, userID uuid.UUID) ([]Friendship, error) {
	rows, err := q.db.QueryContext(ctx, listFriends, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Friendship{}
	for rows.Next() {
		var i Friendship
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.FriendID,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingRequests = `-- name: ListPendingRequests :many
SELECT id, user_id, friend_id, status, created_at, updated_at FROM friendships
WHERE friend_id = $1 AND status = 'pending'
ORDER BY created_at DESC
`

func (q *Queries) ListPendingRequests(ctx context.Context, friendID uuid.UUID) ([]Friendship, error) {
	rows, err := q.db.QueryContext(ctx, listPendingRequests, friendID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Friendship{}
	for rows.Next() {
		var i Friendship
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.FriendID,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFriendshipStatus = `-- name: UpdateFriendshipStatus :one
UPDATE friendships SET status = $1, updated_at = now()
WHERE id = $2
RETURNING id, user_id, friend_id, status, created_at, updated_at
`

type UpdateFriendshipStatusParams struct {
	Status string    `json:"status"`
	ID     uuid.UUID `json:"id"`
}

func (q *Queries) UpdateFriendshipStatus(ctx context.Context, arg UpdateFriendshipStatusParams) (Friendship, error) {
	row := q.db.QueryRowContext(ctx, updateFriendshipStatus, arg.Status, arg.ID)
	var i Friendship
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FriendID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
