// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: leaderboard.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const createLeaderboardConfig = `-- name: CreateLeaderboardConfig :one
INSERT INTO leaderboard_configs (code, name, update_strategy, max_entries, metadata)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, code, name, update_strategy, max_entries, metadata, created_at, updated_at
`

type CreateLeaderboardConfigParams struct {
	Code           string                `json:"code"`
	Name           string                `json:"name"`
	UpdateStrategy string                `json:"update_strategy"`
	MaxEntries     sql.NullInt32         `json:"max_entries"`
	Metadata       pqtype.NullRawMessage `json:"metadata"`
}

func (q *Queries) CreateLeaderboardConfig(ctx context.Context, arg CreateLeaderboardConfigParams) (LeaderboardConfig, error) {
	row := q.db.QueryRowContext(ctx, createLeaderboardConfig,
		arg.Code,
		arg.Name,
		arg.UpdateStrategy,
		arg.MaxEntries,
		arg.Metadata,
	)
	var i LeaderboardConfig
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.UpdateStrategy,
		&i.MaxEntries,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createScore = `-- name: CreateScore :one
INSERT INTO leaderboard_scores (board_id, user_id, score)
VALUES ($1, $2, $3)
RETURNING id, board_id, user_id, score, submitted_at
`

type CreateScoreParams struct {
	BoardID uuid.UUID `json:"board_id"`
	UserID  uuid.UUID `json:"user_id"`
	Score   float64   `json:"score"`
}

func (q *Queries) CreateScore(ctx context.Context, arg CreateScoreParams) (LeaderboardScore, error) {
	row := q.db.QueryRowContext(ctx, createScore, arg.BoardID, arg.UserID, arg.Score)
	var i LeaderboardScore
	err := row.Scan(
		&i.ID,
		&i.BoardID,
		&i.UserID,
		&i.Score,
		&i.SubmittedAt,
	)
	return i, err
}

const getLeaderboardConfig = `-- name: GetLeaderboardConfig :one
SELECT id, code, name, update_strategy, max_entries, metadata, created_at, updated_at FROM leaderboard_configs WHERE code = $1
`

func (q *Queries) GetLeaderboardConfig(ctx context.Context, code string) (LeaderboardConfig, error) {
	row := q.db.QueryRowContext(ctx, getLeaderboardConfig, code)
	var i LeaderboardConfig
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.UpdateStrategy,
		&i.MaxEntries,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listLeaderboardConfigs = `-- name: ListLeaderboardConfigs :many
SELECT id, code, name, update_strategy, max_entries, metadata, created_at, updated_at FROM leaderboard_configs ORDER BY name
`

func (q *Queries) ListLeaderboardConfigs(ctx context.Context) ([]LeaderboardConfig, error) {
	rows, err := q.db.QueryContext(ctx, listLeaderboardConfigs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LeaderboardConfig{}
	for rows.Next() {
		var i LeaderboardConfig
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.UpdateStrategy,
			&i.MaxEntries,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
