// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type Credential struct {
	ID         uuid.UUID      `json:"id"`
	UserID     uuid.UUID      `json:"user_id"`
	Type       string         `json:"type"`
	Identifier string         `json:"identifier"`
	SecretHash sql.NullString `json:"secret_hash"`
	Verified   bool           `json:"verified"`
	CreatedAt  time.Time      `json:"created_at"`
}

type LeaderboardConfig struct {
	ID             uuid.UUID             `json:"id"`
	Code           string                `json:"code"`
	Name           string                `json:"name"`
	UpdateStrategy string                `json:"update_strategy"`
	MaxEntries     sql.NullInt32         `json:"max_entries"`
	Metadata       pqtype.NullRawMessage `json:"metadata"`
	CreatedAt      time.Time             `json:"created_at"`
	UpdatedAt      time.Time             `json:"updated_at"`
}

type LeaderboardScore struct {
	ID          uuid.UUID `json:"id"`
	BoardID     uuid.UUID `json:"board_id"`
	UserID      uuid.UUID `json:"user_id"`
	Score       float64   `json:"score"`
	SubmittedAt time.Time `json:"submitted_at"`
}

type PlatformBinding struct {
	ID             uuid.UUID             `json:"id"`
	UserID         uuid.UUID             `json:"user_id"`
	Platform       string                `json:"platform"`
	PlatformUserID string                `json:"platform_user_id"`
	AccessToken    string                `json:"access_token"`
	RefreshToken   string                `json:"refresh_token"`
	ExpiresAt      sql.NullTime          `json:"expires_at"`
	Metadata       pqtype.NullRawMessage `json:"metadata"`
	CreatedAt      time.Time             `json:"created_at"`
	UpdatedAt      time.Time             `json:"updated_at"`
}

type User struct {
	ID          uuid.UUID             `json:"id"`
	Username    string                `json:"username"`
	Email       sql.NullString        `json:"email"`
	Phone       sql.NullString        `json:"phone"`
	DisplayName sql.NullString        `json:"display_name"`
	AvatarUrl   sql.NullString        `json:"avatar_url"`
	Status      string                `json:"status"`
	Metadata    pqtype.NullRawMessage `json:"metadata"`
	CreatedAt   time.Time             `json:"created_at"`
	UpdatedAt   time.Time             `json:"updated_at"`
}

type UserSession struct {
	ID               uuid.UUID      `json:"id"`
	UserID           uuid.UUID      `json:"user_id"`
	RefreshTokenHash string         `json:"refresh_token_hash"`
	DeviceID         sql.NullString `json:"device_id"`
	IpAddress        sql.NullString `json:"ip_address"`
	UserAgent        sql.NullString `json:"user_agent"`
	ExpiresAt        time.Time      `json:"expires_at"`
	RevokedAt        sql.NullTime   `json:"revoked_at"`
	CreatedAt        time.Time      `json:"created_at"`
}
