// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: platform_bindings.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const countUserCredentials = `-- name: CountUserCredentials :one
SELECT COUNT(*) FROM credentials WHERE user_id = $1
`

func (q *Queries) CountUserCredentials(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUserCredentials, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPlatformBinding = `-- name: CreatePlatformBinding :one
INSERT INTO platform_bindings (user_id, platform, platform_user_id, access_token, refresh_token, expires_at, metadata)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, user_id, platform, platform_user_id, access_token, refresh_token, expires_at, metadata, created_at, updated_at
`

type CreatePlatformBindingParams struct {
	UserID         uuid.UUID             `json:"user_id"`
	Platform       string                `json:"platform"`
	PlatformUserID string                `json:"platform_user_id"`
	AccessToken    string                `json:"access_token"`
	RefreshToken   string                `json:"refresh_token"`
	ExpiresAt      sql.NullTime          `json:"expires_at"`
	Metadata       pqtype.NullRawMessage `json:"metadata"`
}

func (q *Queries) CreatePlatformBinding(ctx context.Context, arg CreatePlatformBindingParams) (PlatformBinding, error) {
	row := q.db.QueryRowContext(ctx, createPlatformBinding,
		arg.UserID,
		arg.Platform,
		arg.PlatformUserID,
		arg.AccessToken,
		arg.RefreshToken,
		arg.ExpiresAt,
		arg.Metadata,
	)
	var i PlatformBinding
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Platform,
		&i.PlatformUserID,
		&i.AccessToken,
		&i.RefreshToken,
		&i.ExpiresAt,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePlatformBinding = `-- name: DeletePlatformBinding :one
DELETE FROM platform_bindings WHERE user_id = $1 AND platform = $2
RETURNING id, user_id, platform, platform_user_id, access_token, refresh_token, expires_at, metadata, created_at, updated_at
`

type DeletePlatformBindingParams struct {
	UserID   uuid.UUID `json:"user_id"`
	Platform string    `json:"platform"`
}

func (q *Queries) DeletePlatformBinding(ctx context.Context, arg DeletePlatformBindingParams) (PlatformBinding, error) {
	row := q.db.QueryRowContext(ctx, deletePlatformBinding, arg.UserID, arg.Platform)
	var i PlatformBinding
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Platform,
		&i.PlatformUserID,
		&i.AccessToken,
		&i.RefreshToken,
		&i.ExpiresAt,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPlatformBinding = `-- name: GetPlatformBinding :one
SELECT id, user_id, platform, platform_user_id, access_token, refresh_token, expires_at, metadata, created_at, updated_at FROM platform_bindings WHERE platform = $1 AND platform_user_id = $2
`

type GetPlatformBindingParams struct {
	Platform       string `json:"platform"`
	PlatformUserID string `json:"platform_user_id"`
}

func (q *Queries) GetPlatformBinding(ctx context.Context, arg GetPlatformBindingParams) (PlatformBinding, error) {
	row := q.db.QueryRowContext(ctx, getPlatformBinding, arg.Platform, arg.PlatformUserID)
	var i PlatformBinding
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Platform,
		&i.PlatformUserID,
		&i.AccessToken,
		&i.RefreshToken,
		&i.ExpiresAt,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPlatformBindingsByUserID = `-- name: GetPlatformBindingsByUserID :many
SELECT id, user_id, platform, platform_user_id, access_token, refresh_token, expires_at, metadata, created_at, updated_at FROM platform_bindings WHERE user_id = $1
`

func (q *Queries) GetPlatformBindingsByUserID(ctx context.Context, userID uuid.UUID) ([]PlatformBinding, error) {
	rows, err := q.db.QueryContext(ctx, getPlatformBindingsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PlatformBinding{}
	for rows.Next() {
		var i PlatformBinding
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Platform,
			&i.PlatformUserID,
			&i.AccessToken,
			&i.RefreshToken,
			&i.ExpiresAt,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
