// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AddRoomMember(ctx context.Context, arg AddRoomMemberParams) (ChatRoomMember, error)
	CountUserCredentials(ctx context.Context, userID uuid.UUID) (int64, error)
	CreateChatMessage(ctx context.Context, arg CreateChatMessageParams) (ChatMessage, error)
	CreateChatRoom(ctx context.Context, arg CreateChatRoomParams) (ChatRoom, error)
	CreateCredential(ctx context.Context, arg CreateCredentialParams) (Credential, error)
	CreateLeaderboardConfig(ctx context.Context, arg CreateLeaderboardConfigParams) (LeaderboardConfig, error)
	CreatePlatformBinding(ctx context.Context, arg CreatePlatformBindingParams) (PlatformBinding, error)
	CreateScore(ctx context.Context, arg CreateScoreParams) (LeaderboardScore, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (UserSession, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeletePlatformBinding(ctx context.Context, arg DeletePlatformBindingParams) (PlatformBinding, error)
	GetChatMessages(ctx context.Context, arg GetChatMessagesParams) ([]ChatMessage, error)
	GetChatRoom(ctx context.Context, id uuid.UUID) (ChatRoom, error)
	GetCredentialByTypeIdentifier(ctx context.Context, arg GetCredentialByTypeIdentifierParams) (Credential, error)
	GetCredentialsByUserID(ctx context.Context, userID uuid.UUID) ([]Credential, error)
	GetLeaderboardConfig(ctx context.Context, code string) (LeaderboardConfig, error)
	GetPlatformBinding(ctx context.Context, arg GetPlatformBindingParams) (PlatformBinding, error)
	GetPlatformBindingsByUserID(ctx context.Context, userID uuid.UUID) ([]PlatformBinding, error)
	GetRoomMembers(ctx context.Context, roomID uuid.UUID) ([]ChatRoomMember, error)
	GetSessionByID(ctx context.Context, id uuid.UUID) (UserSession, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	ListLeaderboardConfigs(ctx context.Context) ([]LeaderboardConfig, error)
	RemoveRoomMember(ctx context.Context, arg RemoveRoomMemberParams) (ChatRoomMember, error)
	RevokeSession(ctx context.Context, id uuid.UUID) (UserSession, error)
	RevokeSessionsByUserID(ctx context.Context, userID uuid.UUID) ([]UserSession, error)
	SearchUsers(ctx context.Context, arg SearchUsersParams) ([]User, error)
	UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error)
	UpdateUserStatus(ctx context.Context, arg UpdateUserStatusParams) (User, error)
}

var _ Querier = (*Queries)(nil)
