// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AddRoomMember(ctx context.Context, arg AddRoomMemberParams) (ChatRoomMember, error)
	CountUserCredentials(ctx context.Context, userID uuid.UUID) (int64, error)
	CreateAdminUser(ctx context.Context, arg CreateAdminUserParams) (AdminUser, error)
	CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (AuditLog, error)
	CreateChatMessage(ctx context.Context, arg CreateChatMessageParams) (ChatMessage, error)
	CreateChatRoom(ctx context.Context, arg CreateChatRoomParams) (ChatRoom, error)
	CreateCredential(ctx context.Context, arg CreateCredentialParams) (Credential, error)
	CreateFriendship(ctx context.Context, arg CreateFriendshipParams) (Friendship, error)
	CreateLeaderboardConfig(ctx context.Context, arg CreateLeaderboardConfigParams) (LeaderboardConfig, error)
	CreatePlatformBinding(ctx context.Context, arg CreatePlatformBindingParams) (PlatformBinding, error)
	CreateScore(ctx context.Context, arg CreateScoreParams) (LeaderboardScore, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (UserSession, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteFriendship(ctx context.Context, id uuid.UUID) (Friendship, error)
	DeletePlatformBinding(ctx context.Context, arg DeletePlatformBindingParams) (PlatformBinding, error)
	GetAdminByUsername(ctx context.Context, username string) (AdminUser, error)
	GetChatMessages(ctx context.Context, arg GetChatMessagesParams) ([]ChatMessage, error)
	GetChatRoom(ctx context.Context, id uuid.UUID) (ChatRoom, error)
	GetCredentialByTypeIdentifier(ctx context.Context, arg GetCredentialByTypeIdentifierParams) (Credential, error)
	GetCredentialsByUserID(ctx context.Context, userID uuid.UUID) ([]Credential, error)
	GetFriendship(ctx context.Context, id uuid.UUID) (Friendship, error)
	GetLeaderboardConfig(ctx context.Context, code string) (LeaderboardConfig, error)
	GetPlatformBinding(ctx context.Context, arg GetPlatformBindingParams) (PlatformBinding, error)
	GetPlatformBindingsByUserID(ctx context.Context, userID uuid.UUID) ([]PlatformBinding, error)
	GetRoomMembers(ctx context.Context, roomID uuid.UUID) ([]ChatRoomMember, error)
	GetSessionByID(ctx context.Context, id uuid.UUID) (UserSession, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]AuditLog, error)
	ListFriends(ctx context.Context, userID uuid.UUID) ([]Friendship, error)
	ListLeaderboardConfigs(ctx context.Context) ([]LeaderboardConfig, error)
	ListPendingRequests(ctx context.Context, friendID uuid.UUID) ([]Friendship, error)
	RemoveRoomMember(ctx context.Context, arg RemoveRoomMemberParams) (ChatRoomMember, error)
	RevokeSession(ctx context.Context, id uuid.UUID) (UserSession, error)
	RevokeSessionsByUserID(ctx context.Context, userID uuid.UUID) ([]UserSession, error)
	SearchUsers(ctx context.Context, arg SearchUsersParams) ([]User, error)
	UpdateFriendshipStatus(ctx context.Context, arg UpdateFriendshipStatusParams) (Friendship, error)
	UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error)
	UpdateUserStatus(ctx context.Context, arg UpdateUserStatusParams) (User, error)
}

var _ Querier = (*Queries)(nil)
