// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: sessions.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createSession = `-- name: CreateSession :one
INSERT INTO user_sessions (user_id, refresh_token_hash, device_id, ip_address, user_agent, expires_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, refresh_token_hash, device_id, ip_address, user_agent, expires_at, revoked_at, created_at
`

type CreateSessionParams struct {
	UserID           uuid.UUID      `json:"user_id"`
	RefreshTokenHash string         `json:"refresh_token_hash"`
	DeviceID         sql.NullString `json:"device_id"`
	IpAddress        sql.NullString `json:"ip_address"`
	UserAgent        sql.NullString `json:"user_agent"`
	ExpiresAt        time.Time      `json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (UserSession, error) {
	row := q.db.QueryRowContext(ctx, createSession,
		arg.UserID,
		arg.RefreshTokenHash,
		arg.DeviceID,
		arg.IpAddress,
		arg.UserAgent,
		arg.ExpiresAt,
	)
	var i UserSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshTokenHash,
		&i.DeviceID,
		&i.IpAddress,
		&i.UserAgent,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getSessionByID = `-- name: GetSessionByID :one
SELECT id, user_id, refresh_token_hash, device_id, ip_address, user_agent, expires_at, revoked_at, created_at FROM user_sessions WHERE id = $1
`

func (q *Queries) GetSessionByID(ctx context.Context, id uuid.UUID) (UserSession, error) {
	row := q.db.QueryRowContext(ctx, getSessionByID, id)
	var i UserSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshTokenHash,
		&i.DeviceID,
		&i.IpAddress,
		&i.UserAgent,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const revokeSession = `-- name: RevokeSession :one
UPDATE user_sessions SET revoked_at = now()
WHERE id = $1 AND revoked_at IS NULL
RETURNING id, user_id, refresh_token_hash, device_id, ip_address, user_agent, expires_at, revoked_at, created_at
`

func (q *Queries) RevokeSession(ctx context.Context, id uuid.UUID) (UserSession, error) {
	row := q.db.QueryRowContext(ctx, revokeSession, id)
	var i UserSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshTokenHash,
		&i.DeviceID,
		&i.IpAddress,
		&i.UserAgent,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const revokeSessionsByUserID = `-- name: RevokeSessionsByUserID :many
UPDATE user_sessions SET revoked_at = now()
WHERE user_id = $1 AND revoked_at IS NULL
RETURNING id, user_id, refresh_token_hash, device_id, ip_address, user_agent, expires_at, revoked_at, created_at
`

func (q *Queries) RevokeSessionsByUserID(ctx context.Context, userID uuid.UUID) ([]UserSession, error) {
	rows, err := q.db.QueryContext(ctx, revokeSessionsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserSession{}
	for rows.Next() {
		var i UserSession
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.RefreshTokenHash,
			&i.DeviceID,
			&i.IpAddress,
			&i.UserAgent,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
